<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEt0EV2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEt0EV2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEt0EV2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEt0EV2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEt0EV2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'Et0EV2x',
    'container.build_id' => '76fd8e81',
    'container.build_time' => 1615240357,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEt0EV2x');
